# Consolidate the common configuration for reuse across multiple steps.
definitions:
  # Configure some default step values.
  step-defaults: &step-defaults
    timeout_in_minutes: 15
    retry:
      manual:
        permit_on_passed: true
  plugins:
    ecr: &ecr
      ecr#v2.0.0:
        login: true
        no-include-email: true
steps:
  - label: ":git: Deploy"
    depends_on: "building-image"
    <<: *step-defaults
    concurrency: 1
    concurrency_group: '$BUILDKITE_PIPELINE_SLUG/$BUILDKITE_BRANCH/deploy'
    branches:
      - live
      - main
      - integration
    plugins:
      # Log into ECR for this build step to access and push images.
      - *ecr

      # Download the prebuilt image and extract project files to the
      # local filesystem for further operations.
      - forumone/extract#v0.2.0:
          image: ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}
          from: /var/www/html
          to: ${ARTIFACT_LOCATION}

      # Execute an artifact deployment using the defined branch to
      # environment mapping.
      - forumone/artifact-push#v0.3.1:
          verbose: false
          source-directory: ${ARTIFACT_LOCATION}
          remote: oregonzoo2@svn-45197.prod.hosting.acquia.com:oregonzoo2.git
          branches:
            - match: integration
              target: integration
            - match: main
              target: master
            - match: live
              target: live
          ssh:
            keyscan: svn-45197.prod.hosting.acquia.com
          git:
            name: F1 Builder
            email: support+f1builder@forumone.com

          files:
            force-add:
              - vendor
              - docroot
              - docroot/sites/default/settings.php
