# Design Tokens
# Define basic design variables here.
theme:
  # Breakpoint values for media queries
  # Key names base on Bootstrap Variables
  # https://getbootstrap.com/docs/5.0/layout/breakpoints/
  #
  # Breakpoints should be consistent with README.md and minima.breakpoints.yml.
  breakpoints:
    xs: 0
    sm: 480px
    md: 770px
    lg: 992px
    xl: 1300px
    max: 1600px
  constrains:
    sm: 800px
    md: 1440px
    lg: 2200px
  # Box styles
  box-border:
    standard: 1px solid var(--color--border--standard) #minima-grayscale(gray-50)
    light: 1px solid var(--color--border--light) #minima-grayscale(gray-90)
    dark: 1px solid var(--color--border--dark) #minima-grayscale(gray-20)
    primary-bold: 4px solid var(--color--primary--p-100)
  box-shadow:
    0: none
    1: 0 1px 4px rgba(52, 53, 49, 0.1)
    2: 0 4px 8px rgba(52, 53, 49, 0.1)
    3: 0 8px 16px rgba(52, 53, 49, 0.1)
    4: 0 12px 24px rgba(52, 53, 49, 0.1)
    5: 0 16px 32px rgba(52, 53, 49, 0.1)
  border-radius:
    0: 0
    sm: 4px
    md: 8px
    lg: 12px
  # Opacity tokens
  opacity:
    0: 0
    10: 0.1
    20: 0.2
    30: 0.3
    40: 0.4
    50: 0.5
    60: 0.6
    70: 0.7
    80: 0.8
    90: 0.9
    100: 1
  # Palette object for color values
  palette:
    named:
      cornflower-l-96: hsl(245, 68%, 96%)
      cornflower-l-86: hsl(244, 66%, 86%)
      cornflower-l-76: hsl(244, 66%, 76%)
      cornflower-l-63: hsl(244, 66%, 63%)
      cornflower-l-50: hsl(244, 55%, 50%)
      cornflower-l-46: hsl(244, 50%, 46%)
      cornflower-l-33: hsl(244, 66%, 33%)
      true-fir-l-92: hsl(149, 59%, 92%)
      true-fir-l-90: hsl(148, 58%, 90%)
      true-fir-l-80: hsl(149, 59%, 80%)
      true-fir-l-55: hsl(149, 35%, 55%)
      true-fir-l-40: hsl(149, 55%, 40%)
      true-fir-l-37: hsl(150, 42%, 36%)
      true-fir-l-25: hsl(149, 42%, 25%)
      true-fir-l-15: hsl(149, 42%, 15%)
      chinook-l-90: hsl(6, 92%, 90%)
      chinook-l-80: hsl(6, 92%, 80%)
      chinook-l-71: hsl(6, 93%, 71%)
      chinook-l-51: hsl(6, 58%, 51%)
      chinook-l-25: hsl(6, 58%, 25%)
      japanese-laurel-l-85: hsl(100, 89%, 85%)
      japanese-laurel-l-35: hsl(100, 89%, 35%)
      amber-l-50: hsl(45, 100%, 50%)
      honied-white-l-90: hsl(42, 88%, 90%)
      venetian-red-l-90: hsl(354, 84%, 90%)
      venetian-red-l-45: hsl(354, 85%, 45%)
      venetian-red-l-30: hsl(354, 86%, 30%)
      blue-l-55: hsl(207, 97%, 55%)
      cloudless-l-90: hsl(213, 88%, 90%)
      navy-blue-l-37: hsl(210, 100%, 37%)
      navy-blue-l-25: hsl(210, 100%, 25%)
      prussian-blue-l-28: hsl(230, 100%, 14%)
      windsor-l-57: hsl(259, 54%, 37%)
      blue-violet-l-87: hsl(285, 71%, 55%)
    grayscale:
      white: hsl(0, 0%, 100%)
      gray-100: hsl(60, 3%, 100%)
      gray-95: hsl(60, 3%, 95%)
      gray-90: hsl(60, 3%, 90%)
      gray-80: hsl(60, 3%, 80%)
      gray-70: hsl(60, 3%, 70%)
      gray-60: hsl(60, 3%, 60%)
      gray-50: hsl(60, 3%, 50%)
      gray-40: hsl(60, 3%, 40%)
      gray-30: hsl(60, 3%, 30%)
      gray-20: hsl(60, 3%, 20%)
      gray-10: hsl(60, 3%, 10%)
      gray-0: hsl(60, 3%, 0%)
      black: hsl(0, 0%, 0%)
  ui-palette:
    core:
      background: grayscale.white
      text: grayscale.gray-40
      text-reversed-out: grayscale.white
    primary:
      p-125: named.true-fir-l-25
      p-100: named.true-fir-l-37
      p-50: named.true-fir-l-55
      p-25: named.true-fir-l-90
    secondary:
      p-125: named.cornflower-l-50
      p-100: named.cornflower-l-63
      p-50: named.cornflower-l-76
      p-25: named.cornflower-l-86
      p-10: named.cornflower-l-96
    accent:
      p-125: named.chinook-l-51
      p-100: named.chinook-l-71
      p-50: named.chinook-l-80
      p-25: named.chinook-l-90
    semantic:
      success: named.japanese-laurel-l-35
      error: named.venetian-red-l-45
      warning: named.amber-l-50
      warning-light: named.honied-white-l-90
      message: named.blue-l-55
      message-light: named.cloudless-l-90
    ui:
      link: named.navy-blue-l-37
      hover: named.navy-blue-l-25
      active: named.prussian-blue-l-28
      visited: named.windsor-l-57
      focus: named.blue-violet-l-87
    metro-brand:
      footer-bg-top: grayscale.gray-95
      footer-bg-bottom: grayscale.gray-80
      footer-text: grayscale.gray-30
    border:
      extra-light: grayscale.gray-100
      light: grayscale.gray-90
      somewhat-light: grayscale.gray-70
      standard: grayscale.gray-50
      dark: grayscale.gray-20
      darkest: grayscale.black
    component:
      alert:
        icon: grayscale.black
        text: grayscale.gray-10
        title: grayscale.black
      button:
        default:
          background-active: grayscale.black
          border: grayscale.gray-80
          text: grayscale.white
          text-disabled: grayscale.white
          text-hover: grayscale.white
        secondary:
          text: grayscale.white
          text-hover: grayscale.white
        tertiary:
          background: grayscale.white
          background-hover: grayscale.gray-40
          border: grayscale.black
          border-disabled: grayscale.gray-20
          text: grayscale.gray-30
          text-hover: grayscale.white
        danger:
          background: named.venetian-red-l-45
          background-hover: named.venetian-red-l-30
          text: grayscale.white
          text-hover: grayscale.white
      form:
        background: grayscale.gray-90
      language-picker:
        text: grayscale.gray-30
        hover: grayscale.white
        hover-background: grayscale.gray-50
      link:
        back-to-top:
          background-small: named.cornflower-l-33
          text: grayscale.black
          text-small: grayscale.white
      local-tasks:
        background: grayscale.gray-100
        background-large: grayscale.white
      menu:
        sub-menu-background: grayscale.gray-100
      search-box:
        icon-color: grayscale.gray-40
      summary-box:
        marker: grayscale.black
        text: grayscale.gray-20
      tabs:
        background-gradient-start: grayscale.white
        background-gradient-end: grayscale.gray-90
        background-interactive: grayscale.gray-95
        link: grayscale.gray-30
        link-active: grayscale.gray-20
      text:
        small: grayscale.gray-20
  ui-palette--dark:
    core:
      background: grayscale.white
  #      text: grayscale.gray-80
  #      text-reversed-out: grayscale.black
  # Typography Tokens
  typography:
    base-font-size: 16px
    font-family:
      primary:
        name: primary
        stack: '"Merriweather", georgia, times, "Times New Roman", serif'
        condensed: 87.5
        expanded: 112.5
      secondary:
        name: secondary
        stack: '"EncodeSans", "HelveticaNeue", "Helvetica", "Arial", sans-serif'
        condensed: 75
        expanded: 125
      monospace:
        name: monospace
        stack: '"FiraCode", mono'
        condensed: 100
        expanded: 100
    line-height:
      tight: 1.1
      base: 1.5
      loose: 1.75
    font-size:
      10: 12px
      15: 14px
      20: 16px
      25: 18px
      30: 20px
      40: 24px
      45: 28px
      50: 32px
      60: 40px
      70: 48px
      80: 54px
      90: 64px
      100: 80px
    font-weight:
      light: 300
      regular: 400
      semibold: 600
      bold: 700
  # Transition and animation tokens
  transitions:
    ease:
      ease-in-out: 'cubic-bezier(0.45, 0, 0.55, 1)'
      ease-out: 'cubic-bezier(0.5, 1, 0.89, 1)'
      ease-in: 'cubic-bezier(0.11, 0, 0.5, 0)'
    duration:
      shortest: 150ms
      short: 200ms
      standard: 375ms
      long: 400ms
      longest: 500ms
  # Z index token
  z-index:
    standard: 0
    ui-focus: 200
    # Drupal contextual menus: 300
    drawer: 400
    # Gin toolbar: 501
    nav: 800
    modal: 1600
  # Spacing tokens
  space:
    25: 2px
    50: 4px
    100: 8px
    150: 12px
    200: 16px
    250: 20px
    300: 24px
    400: 32px
    450: 36px
    500: 40px
    600: 48px
    700: 56px
    800: 64px
    1000: 80px
    1200: 96px
  # Scaling tokens
  scale:
    mobile: 1.2
    desktop: 1.0
