'use strict';

const path = require('path');
const os = require('os');
const util = require('util');
const fs = require('fs');
const yaml = require('yaml');

const readSource = require('./readSource');
const transform = require('./transform');
const renderSass = require('./renderSass');
const renderCustomProperties = require('./renderCustomProperties');

const writeFile = util.promisify(fs.writeFile);

const buildToken = async () => {
  const scssDir = path.join(__dirname, '../components');

  const parsed = await readSource(
    path.join(__dirname, '../components/00-base/config.design-tokens.yml'),
  );

  const sassComment = `// DO NOT EDIT THIS FILE.  This is a gitignored artifact created by NPM.
  // Design tokens should be edited in components/00-base/config.design-tokens.yml`;
  const yamlComment = `# DO NOT EDIT THIS FILE.  This is a gitignored artifact created by Gulp.
# Design tokens should be edited in components/00-base/config.design-tokens.yml`;
  const cssComment = `// CSS Custom properties for colors`;

  const transformed = transform(parsed);

  await Promise.all([
    writeFile(
      path.join(scssDir, '_design-tokens.artifact.scss'),
      sassComment +
        os.EOL +
        renderSass(transformed.data) +
        os.EOL +
        os.EOL +
        cssComment +
        os.EOL +
        renderCustomProperties(transformed.data),
    ),
    writeFile(
      path.join(scssDir, '_design-tokens.artifact.yml'),
      yamlComment + os.EOL + yaml.stringify(transformed.data),
    ),
  ]);
};
buildToken().catch((err) => {
  console.error(err);
});
